version: '2.4'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-jcr:latest
    container_name: artifactory
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./artifactory/:/artifactory_extra_conf/
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8082/artifactory/api/system/ping"]
        start_period: 30s
        interval: 5s
        timeout: 10s
        retries: 30

  jenkins:
    depends_on:
      artifactory:
        condition: service_healthy
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "50000:50000"
      - "8880:8080"
    volumes:
      - ./jenkins_controller/casc.yml:/usr/share/jenkins/ref/casc.yml
      - ./jenkins_controller/jobs:/usr/share/jenkins/ref/jobs
    restart: always

  jenkins-agent:
    depends_on:
      - jenkins
    container_name: jenkins-agent
    build: jenkins_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCbNjJHE1spQ4e+LmXmsGlulxYLssxh+iyzwqN8gMBnI3QvMMvQzFBP22+qLrcebajrSYHZSe6kFazNy/+xGcZLXouQxBRREPNpf1S9nx96mqmmdwRqnNaplScoKcnYEcVOoYXx3graUjSD6FCGHD6+HOrQ5JN93kZGqiTI8aCJ3NydPhZOffMTJeQpAg7kDexs9iIEnqe//xJG4CRpwkkIrHCCq7hMgoW+IEVskX1653YWhGJCnWEY70o6FkRlIdUO0n99YgO3gvPKzaJAvjOFUbvWs1FGrqExarcdPktFDUYtloax3BOGcFQmaUaifDkSBNb5chkyBQVrFwxL0GT0A9Zox6K3ZUHHdAKdewtQzZWO6ahq0xNQHbPAJlYWyvETUqEnnqvVoAnV/OdJoqCpscc9ii4+gHWZBSfLEZYDKu6NHfpxvVHj7qrAmunWvjEqtn9D464IHEbzsAT9Qma2/R8tfXHyzNICt6JU8R8/ugwPf6a5GJg9HN2eWNFqj4i94lqqnM3sbMzwjssKaIATAo7ChyklL2HbYPiH7TwMaaSOD68K6BU1GdJEFIr/OvXk0PIuLwj5i3FVL8ZhZB8vSI50lRYoq872xzhiilV40MnYHvVRW1tUYrAj3e7Nhgx12wwIgSD/xStXBVG+kvVQQ1e+3co/aApYtv3ZhbiRHw==
    restart: always

  sonarqube:
    depends_on:
      - jenkins
    image: sonarqube:9.2.4-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    restart: always

  selenium_hub:
    depends_on:
      - jenkins
    image: selenium/hub
    container_name: selenium_hub
    ports:
    - "4442:4442"
    - "4443:4443"
    - "4444:4444"
    restart: always

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    depends_on:
      - selenium_hub
    environment:
    - SE_EVENT_BUS_HOST=selenium_hub
    - SE_EVENT_BUS_PUBLISH_PORT=4442
    - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    restart: always
